### ISSUE TITLE
edge buffer

### ISSUE THREAD

**Issue by Patryk-B** [KiameV/rimworld-impassablemapmaker#1]
Hi, this is not a bug report just an idea.
Is there a way to set the edge buffer to the "0" value (right now min value is 3).
Also, it would be great if one could set the buffer for each edge (North edge, south edge, etc) respectively.

It would be great if one could create a map with 3 edges covered by a mountain while the 4th edge would be left open (to allow proper functioning of the game).

**Comment by KiameV** [comment]
A buffer of zero causes the game to become unplayable.
I can see about making corners filled with mountain but having entire sides covered could be equally unplayable though i can try it.

**Comment by Patryk-B** [comment]
I am sincerely sorry for my bad English. I believe I wasn't able to share correctly what I had in mind. 

I am well aware that "edge buffer" set to zero will make the game unplayable. 
Each map has 4 edges (North edge, East edge, South edge, and West edge) - my idea was to add the possibility to set the "edge buffer" for each map edge respectively. 

The 2nd part of my idea was to change the minimum value of edge buffer from three to zero.  

As the result, the player will gain the possibility to chose which edge should remain open (edge buffer greater or equal to "6") and which edge should remain closed (edge buffer set to "0").

I also believe as long as at least a single edge is "open" the game will be playable. 

As I said, it's just an idea. Thank you, you became interested in my suggestion.
