### ISSUE TITLE
Nature not generating correctly

### ISSUE THREAD

**Issue by Octofoxy** [KiameV/rimworld-impassablemapmaker#4]
Hello,

I wanted to use your mod to make a base in a dormant volcano (a steam comment got me the idea), which should be free standing in the middle of the map. So I generated a map with a round mountain in the middle, which in turn has a free round area in its center. There's plenty of room between the mountain and the map borders.

However, around the mountain, the nature doesn't seem to be generating right. There are some small spots where there are a few trees and a bit of grass, but the rest is just bare soil, the whole map! The only place that seems to be generating normally is the free center of the mountain.

How could this happen?

**Comment by KiameV** [comment]
Hmm the map generation should be the same throughout, just lots of extra mountain. Let me take a look on my side if I can reproduced

What biome did you use? What about the outside buffer value?
